"""empty message

Revision ID: 4a24a31f8483
Revises: c587052d1893
Create Date: 2021-06-30 21:52:15.466375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a24a31f8483'
down_revision = 'c587052d1893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_created_at'), 'subscribers', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=False)
    op.create_index(op.f('ix_subscribers_hash'), 'subscribers', ['hash'], unique=True)
    op.create_index(op.f('ix_subscribers_status'), 'subscribers', ['status'], unique=False)
    op.create_index(op.f('ix_subscribers_updated_at'), 'subscribers', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_updated_at'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_status'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_hash'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_created_at'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
